[project]
name = "updating-indexes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "langchain>=1.2.3",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.7",
    "langchain-google-vertexai>=3.2.1",
    "langchain-text-splitters>=1.1.0",
    "python-dotenv>=1.2.1",
]
